### ISSUE TITLE
我想加入AO3 Mirror维护

### ISSUE THREAD

**Issue by linwenxuan04** [shujuliu/AO3-Mirror-Site#1]
我本来是一个吃瓜网友，直到AO3直接被墙。。。
现在我暂时可以使用Trojan和V2Ray翻墙获取数据。
所以我可以加入吗:-)
Email ：llwwxxllwwxx@gmail.com

**Comment by ShuJuLiu2001** [comment]
阁下您好，已向您发送更多信息，请及时查看您的邮箱。（￣︶￣）↗
